### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by exalted** [inamiy/YIFullScreenScroll#1]
Follow steps below:
1. [Download](https://github.com/inamiy/YIFullScreenScroll/zipball/master)
2. Open `YIFullScreenScrollDemo.xcodeproj`
3. Hit "Run" in Xcode.

Error message:

```
CompileStoryboard YIFullScreenScrollDemo/en.lproj/MainStoryboard.storyboard
    cd /Users/foo/Downloads/inamiy-YIFullScreenScroll-67d9c88
    setenv IBSC_MINIMUM_COMPATIBILITY_VERSION 5.1
    setenv PATH "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    setenv XCODE_DEVELOPER_USR_PATH /Applications/Xcode.app/Contents/Developer/usr/bin/..
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin/ibtool --errors --warnings --notices --output-format human-readable-text --compile /Users/foo/Library/Developer/Xcode/DerivedData/YIFullScreenScrollDemo-eqbpcfhyablplebpmfgnjihcfkor/Build/Products/Debug-iphonesimulator/YIFullScreenScrollDemo.app/en.lproj/MainStoryboard.storyboardc /Users/foo/Downloads/inamiy-YIFullScreenScroll-67d9c88/YIFullScreenScrollDemo/en.lproj/MainStoryboard.storyboard --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator5.1.sdk

Command /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin/ibtool failed with exit code 255
```

**Comment by inamiy** [comment]
It seems exit-code 255 is not a code issue.

http://stackoverflow.com/questions/8023563/xcode-not-compiling-any-project-clang-failed-with-exit-code-255

And this page (in Japanese) says the error will be fixed by rebooting your Mac. You should try too.

http://iphone-dev.doorblog.jp/archives/3923049.html

**Comment by exalted** [comment]
Okay, I get that this isn't a code issue, but it seems I am not able to get this thing run: reboot won't help. Have you tried a clean download from github and run from a separate working directory your self?

**Comment by inamiy** [comment]
I tried as you mentioned, but I see no problem both in Xcode 4.4.1 and 4.5 (beta 4).
What is your Xcode version? Is this library the only one that can't build & run?

So far I found quite a lot of Q&As with regard to exit-code 255,
but I don't know they really help. It's beyond my control...:(

http://www.google.co.jp/webhp?q=failed%20with%20exit%20code%20255%20xcode

**Comment by exalted** [comment]
Yea, there's lots of voice about the issue all over. I guess you're right. Funny thing is though, I can't build it two separate Macs, I guess there's something wrong with Xcode installer...

**Comment by inamiy** [comment]
I refactored code and updated version to 1.0.0.
Now, demo app uses CocoaPods to build, so please try.
If you still have problems, please create another issue :)

Will close.
