### ISSUE TITLE
Navigation Bar disappears and does not come back...ever

### ISSUE THREAD

**Issue by peoplecallmefrancois** [inamiy/YIFullScreenScroll#10]
In my app, when I scroll down, the navigation bar disappears, but when I scroll up, it is completely gone from the screen.

How do I fix this issue?

Thanks,
Francois

**Comment by inamiy** [comment]
Have you set `self.fullScreenScroll.shouldShowUIBarsOnScrollUp=NO`?
If so, navigationBar will appear only when scrolled to the very first top.

If this doesn't fix your issue, try `[self.fullScreenScroll showUIBarsAnimated:YES]` at some place,
which will display hidden navigationBar manually.

**Comment by inamiy** [comment]
Got the right answer?
I will close this issue and please reopen when needed.
