### ISSUE TITLE
1px line under navBar when scrolled to the bottom

### ISSUE THREAD

**Issue by ghost** [inamiy/YIFullScreenScroll#13]
There appears a 1px line of the navBar (under the hidden navBar), when I scrolled to the bottom. You'll see it, if you turn the background color into black and scroll in the tableView to the bottom.

**Comment by inamiy** [comment]
Thanks, but I couldn't reproduce the issue...
(setting tableView.backgroundColor, window, etc)

Can you send me a demo for this, too?

**Comment by ghost** [comment]
OK, I tested it with my old project (https://github.com/mylittlehero/Issue22.git). Set the contentView of the cell to black. Now swipe down once so the tableView can scroll to bottom in one swipe. When now the scrollView bounces back, you can see 1px of the navBar in the left top corner, where the contentView is blacked out.

Can you see it now?

**Comment by inamiy** [comment]
OK, I finally got it right. Please try!

**Comment by ghost** [comment]
Brilliant :)
