### ISSUE TITLE
Some serious bugs in iOS7

### ISSUE THREAD

**Issue by iimgal** [inamiy/YIFullScreenScroll#14]

**Comment by thecodesharegit** [comment]
noticed that as well

**Comment by inamiy** [comment]
iOS7 is still in beta, so please stay a while until new view-layout really fixes.

**Comment by inamiy** [comment]
I'm currently working on iOS7 fix as well.
(I will keep this issue opened until iOS7 is shipped)

https://github.com/inamiy/YIFullScreenScroll/tree/iOS7
