### ISSUE TITLE
Can't use setBackgroundImage on nav bar on iOS7

### ISSUE THREAD

**Issue by thecodesharegit** [inamiy/YIFullScreenScroll#19]
Seems to be canceled out and I'm getting tint color instead.

**Comment by inamiy** [comment]
Hi. Have you tested the latest version (cb10ee9) ?
I guess this will solve the issue.

**Comment by inamiy** [comment]
Oops, sorry it was 88af69cd24e246ae95fe39676f99caaaa1690c9e

**Comment by thecodesharegit** [comment]
Yep, testing with the latest version.Thank you for responding so quickly.

**Comment by inamiy** [comment]
https://github.com/inamiy/YIFullScreenScroll/tree/demo/navBarBackground

Can you test this commit? I guess it's working fine.
If else, please show me how to reproduce bug.

**Comment by inamiy** [comment]
This is an old issue to close. Please reopen if you find any.
