### ISSUE TITLE
setNeedsStatusBarAppearanceUpdate will make backgroundcolor of navbar black after hide

### ISSUE THREAD

**Issue by uschen** [inamiy/YIFullScreenScroll#20]
with:
[self.navigationController.navigationBar setBarStyle:UIBarStyleBlackTranslucent];
        [self.navigationController.navigationBar setTranslucent:NO];

**Comment by uschen** [comment]
with
[self setExtendedLayoutIncludesOpaqueBars:NO];

**Comment by inamiy** [comment]
Hi, I couldn't figure out how to reproduce bug from your code.
Can you fork current demo & show me a bug?

**Comment by uschen** [comment]
It's kinda difficult to replicate... I tried on various projects and find out for iOS 7 only, without doing [self setExtendedLayoutIncludesOpaqueBars:YES](no storyboard), during/after the navbar scrolled up, there will be a black bar left. I will try to replicate it on the demo project.

**Comment by inamiy** [comment]
OK. I'm looking forward to seeing more from you.

**Comment by uschen** [comment]
can't duplicated on the example project... should close....

**Comment by inamiy** [comment]
OK. Please let me know if you find it again.
