### ISSUE TITLE
iOS 7 Status bar overlaps the view

### ISSUE THREAD

**Issue by jasminelily** [inamiy/YIFullScreenScroll#21]
Can you give me any advice about this?What did I do wrong?Thank you.

https://s3.amazonaws.com/uploads.hipchat.com/41313/277518/NTEJHQ54QH7lOJY/IMG_0289.jpg

**Comment by inamiy** [comment]
That's library's default behavior in iOS7.
NavigationBar-background should disappear when fully scrolled down, and only status-bar will be visible.

**Comment by uschen** [comment]
Just add a uiview to the status bar always or when the navbar disappears.

**Comment by inamiy** [comment]
Good idea :)
Auto-adding status-bar-background (like Facebook app) from library side may be a good new feature.
I will note it.
