### ISSUE TITLE
viewDidAppear is not called

### ISSUE THREAD

**Issue by alper** [inamiy/YIFullScreenScroll#25]
I tried implementing this, but the viewDidAppear is not called in my code (viewWillAppear is called however).

This causes the

```
    self.isViewVisible = YES;
```

not to go through and makes the rest of the code not work. The KVO callback for contentOffset returns without doing anything if isViewVisible is false.

Am I doing anything wrong? I'm stumped by the fact that it would call viewWillAppear and not viewDidAppear.

**Comment by inamiy** [comment]
`-viewDidAppear:` seems to work fine in current demo project.
Can you add the code and reproduce the same bug?

**Comment by alper** [comment]
It turns out my class was not calling viewDidAppear. Thanks!
