### ISSUE TITLE
Does not understand statusbar

### ISSUE THREAD

**Issue by alper** [inamiy/YIFullScreenScroll#26]
When the code does work (I hardcoded some values to fix my previous issue) it does not really take into account the statusbar. The navbar does scroll out of view but because it is not aware of my status bar it does not scroll back entirely.

It only scrolls back the height of the navbar minus the height of the statusbar.

**Comment by inamiy** [comment]
Same for here.
Can you reproduce the bug in demo project?

**Comment by alper** [comment]
In the demo project this looks to be going fine, but for me it's like this:
![ios_simulator__iphone_retina_4inch_64bit__ios_7 0 3_11b508_20140310_102145](https://f.cloud.github.com/assets/72429/2372122/a1211bbe-a835-11e3-8e46-0eb17fe91c96.jpg)
![ios_simulator__iphone_retina_4inch_64bit__ios_7 0 3_11b508_20140310_102214](https://f.cloud.github.com/assets/72429/2372123/a4dc0a48-a835-11e3-9939-8dd6c25979c3.jpg)

I don't understand which setting could affect this.

**Comment by inamiy** [comment]
In your case, I guess you are using `YIFullScreenScrollStyleFacebook` but trying to add UIButtons directly onto UINavigationBar instead of using UIBarButtonItems.

As you can see button's fadeout code [here](https://github.com/inamiy/YIFullScreenScroll/blob/b2152fbc61a744993599acbf75eaedc90f6a58e1/Classes/YIFullScreenScroll.m#L510-L524), they will only fade if they are normal UIBarButtonItems.

If I'm wrong, can you please attach your UIBarButtonItem's code?

**Comment by alper** [comment]
I don't have any code for it, they are just UIBarButtonItems:

![cuppings xcworkspace__mainstoryboard storyboard_20140310_104448](https://f.cloud.github.com/assets/72429/2372317/e42b6bd2-a838-11e3-9138-dcdd2f206e9a.jpg)

**Comment by inamiy** [comment]
Hm, I see...

But current demo project (+ adding UIBarButtonItem in storyboard) still works fine,
so there should be some other reason in your code that breaks default fading behavior.

Adding breakpoint around the fading code and test run will be helpful to you.

**Comment by alper** [comment]
It would seem that obj.customView are nil. Are these supposed to be set somewhere?

**Comment by inamiy** [comment]
I finally found the issue and you were right!
I fixed it in 2f4dc14 , so please try :)

**Comment by pkotesh-systango** [comment]
Hey, I am facing this issue again. I am using a segmented control in the Navigation Bar. Can you please tell me how can I fix this?
