### ISSUE TITLE
TabBar can't hide if use RDVTabBarController

### ISSUE THREAD

**Issue by Sean-Wang** [inamiy/YIFullScreenScroll#31]
In my project, I user RDVTabBarController (https://github.com/robbdimitrov/RDVTabBarController) instead of UITabBar. When I scroll screen, the Tabbar can't hide. Please tell me how to do solve the problem.

**Comment by inamiy** [comment]
I found that `RDVTabBarController` is a customization of UIViewController, not UITabBarController.
Unfortunately, `YIFullScreenScroll` can only handle UINavigationController/UITabBarController's top & bottom UI-bars as default.

To further adjust your custom UI-bar's layout, please see #12 for more detail.
Using `-fullScreenScrollDidLayoutUIBars:` delegate method will help you.

**Comment by milanvdgm** [comment]
u can use this method for hide tabbar 
 [[self rdv_tabBarController] setTabBarHidden:YES animated:YES];
