### ISSUE TITLE
Wrong scrollIndicatorInsets.bottom when set shouldHideTabBarOnScroll=NO

### ISSUE THREAD

**Issue by indevizible** [inamiy/YIFullScreenScroll#32]
Screenshot
![ios simulator screen shot apr 24 2014 4 49 13 pm](https://cloud.githubusercontent.com/assets/1861329/2788112/b7b8f4b8-cb95-11e3-8eca-a515adf3b31f.png)

**Comment by inamiy** [comment]
I guess ebc948b will be all right. Thanks!

**Comment by indevizible** [comment]
Great ! Thanks  :+1:
