### ISSUE TITLE
why my application can not work

### ISSUE THREAD

**Issue by days999** [inamiy/YIFullScreenScroll#34]
The attach is my project, but it can't work normally,where are the problems?(after download, please rename to .zip)

![testfullscrollview](https://cloud.githubusercontent.com/assets/7651009/3035603/4caf5cb4-e091-11e3-9e0b-57f2ff4b75ef.png)

**Comment by inamiy** [comment]
`YIFullScreenScroll` won't activate if `scrollView.contentSize.height` is too short.
In your demo code, try setting numberOfRows = 100 instead of 10.

**Comment by days999** [comment]
Thanks, it's wonderful when i set rows = 100.

2014-05-25 13:08 GMT+08:00 Yasuhiro Inami notifications@github.com:
