### ISSUE TITLE
Custom view frame scrolls off screen.

### ISSUE THREAD

**Issue by mirceamironenco** [inamiy/YIFullScreenScroll#35]
I have a custom view just below the navigation bar. It's not a search bar just a normal view with this frame : {0, 0}, {320, 44};

I'm trying to make it disappear with the navigation bar (if you look at the facebook app it's absolutely identical to the bar they have under the navbar). However using :
- (void)fullScreenScrollDidLayoutUIBars:(YIFullScreenScroll*)fullScreenScroll 
  {
  CGRect newFrame = self.customBar.frame;
  newFrame.origin.y += self.navigationController.navigationBar.frame.size.height;
  self.customBar.frame = newFrame;
  }

Pushes it off screen. (It just keeps adding to the view's y coordinate). How can i make it hide with the navbar , just like facebook does?

**Comment by inamiy** [comment]
Sorry, sample calculation code in README.md seems to be wrong.

It's better you calculate y-coordinate by yourself because it depends on your view hierarchy structure. Grab navigationBar's frame using UIView's converting method e.g. `-convertRect:toView:` to adjust your customView's position on your own.

**Comment by mirceamironenco** [comment]
Alright thanks , i solved it , i will post my code if anyone else is having trouble with this. I had a view just below the navigation bar , exactly like facebook has. Here's what i did : 
- (void)fullScreenScrollDidLayoutUIBars:(YIFullScreenScroll*)fullScreenScroll
  {
  CGRect newFrame = self.customView.frame;
  
  newFrame.origin.y = [self.view convertRect:self.navigationController.navigationBar.frame   fromView:self.view].origin.y + self.navigationController.navigationBar.frame.origin.y-44; (44 was the height of my custom view);

self.customView.frame = newFrame;

}
This basically works if you want the view to be exactly below the navbar, like a searchBar would.

@inamiy if you have any improvements for this please let me know.Thanks!

Edit : Like @inamiy  said this is very much dependent on your view hierarchy structure though.

Edit2: Removed unnecessary code.
