### ISSUE TITLE
Is any application using this implementation?

### ISSUE THREAD

**Issue by bkoc** [inamiy/YIFullScreenScroll#6]
Did you use this implementation in any of your apps?

We are manipulating uitransitionview of the uitabbarcontroller... Is this allowed by apple or is it risky?

**Comment by inamiy** [comment]
This library is used in my [WordBook](https://itunes.apple.com/jp/app/id495453330?mt=8) app, and you can try it for free :)

By the way, manipulating private-view-hierarchy is not restricted by Apple, 
but may be risky when new iOS version has totally different view-structure, 
especially in `UINavigationController` and `UITabBarController`.

If such big changes happen in next iOS7 for example, you will need a version fix and upload as a new app-binary.
But you should also keep in mind that we always have such kind of fixes no matter what code we write :)
