### ISSUE TITLE
UITabBar over UITableView

### ISSUE THREAD

**Issue by ghost** [inamiy/YIFullScreenScroll#7]
In UITableView 1 I am using your YIFullScreenScroll. When I now select a cell, which pushes me to the next view (I don't know if it has to be another UITableView or simply a UIScrollView - in my example it is a tableView..), the view does not recalculate the UITabBar height. It seems, the tabBar is just set over the view and hiding it - the scrollBar is the best evidence..
- when I then close the app and reopen it, the whole view is stuck: no more scrolling possible.

GREAT code by the way :) would be pleased to use it in my upcoming project.

**Comment by inamiy** [comment]
> the view does not recalculate the UITabBar height. It seems, the tabBar is just set over the view and hiding it - the scrollBar is the best evidence

Sorry, I couldn't figure out this situation. 
What will be the 2nd viewController.view.frame like when first appeared? 
Does tabBar still change its position via scroll but shows black window-background?
It will be nice if you can fork this repository and reproduce the bug with current demo project.

By the way, current spec is as follows, which may be a hint for you (I will add this in README later):

```
From version 1.0.0, `YIFullScreenScroll` enables/disables its functionality when `viewWillAppear` or `viewWillDisappear` is called.
This means, fullscreen will not continue to the next pushed (2nd) viewController, 
and if you want to keep it, you also need to setup `self.fullScreenScroll` to the 2nd viewController's `viewDidLoad`.
```

> GREAT code by the way :) would be pleased to use it in my upcoming project.

Thanks :)

**Comment by ghost** [comment]
Normally the frame.size.height is 445 without your code - with your code it is 548.

No, the code is not active anymore, so no bar is hiding.

I'll try to fork it asap :)

## EDIT

If I set self.fullScreenScroll.shouldHideTabBarOnScroll = NO; --> everything works fine :)

## EDIT

I now found the code which causes the problem:

// tabBar
UITabBar\* tabBar = self.tabBar;

CGRect frame = _viewController.tabBarController.view.bounds;
frame.size.height -= tabBar.height;
tabBarTransitionView.frame = frame;

// scrollIndicatorInsets will be modified when tabBarTransitionView shrinks, so reset it here.
_scrollView.scrollIndicatorInsets = _defaultScrollIndicatorInsets;

Somehow this code affects the behavior of the next view's tabBar.

**Comment by inamiy** [comment]
`shouldHideTabBarOnScroll=YES` will force tabBarController's childViewController.view to expand its frame till tabBar's bottom, so this code might have messed up the nav-pushed (2nd) viewController's view.frame, though it is still a required method.

I still need to see the bug-reproduced code to examine carefully, but my current guess is that there may exist a race-condition between
- 1st viewController disappearing (disabling fullScreenScroll in viewWill/DidDisappear)
- 2nd viewController appearing (enabling fullScreenScroll in viewWill/DidAppear)

which leads 2nd viewController's frame size as fullscreen but not hideable in certain case.

Thus, my suggestion to hotfix this issue is to force-set `self(1st).fullScreenScroll.enabled = NO` on every `pushViewController` since viewWillDisappear/viewDidDisappear as disabling timing seems not reliable.

**Comment by ghost** [comment]
You easily can rebuild this situation on a TabBarController based project: Use your code in a tableView. When you click on a cell, use another tableView or simply a scrollView in the next view. You'll see the scrollBar behind the tabBar.

**Comment by inamiy** [comment]
I modified a demo app to test your navigation-push on https://github.com/inamiy/YIFullScreenScroll/commit/nav-test.
Try setting ENABLE_FULLSCREEN macro in `FirstDetailViewController` and see if it's working as you expected.

**Comment by ghost** [comment]
Yasuhiro, I now made a slight project, to show you the issue.

Issue:

If I scroll in the view, which uses your code and go one step back, the other scrollViews in other tabs in the tabBar seem to go crazy. The scrollBars can go behind the tabBar.

How to see the Issue:
- open the app (https://github.com/mylittlehero/FullScreenTabBarIssue2.git)
- choose a cell in the tab "shop"
- now go back again
- tap on the tab "Item" --> when you scroll now, you'll see the scrollBar hiding behind the tabBar.

Would be great if you could fix that _-_

**Comment by inamiy** [comment]
Thanks. I saw your demo and I will investigate this issue.

**Comment by inamiy** [comment]
Please try 1861700. I guess this will work :)

**Comment by ghost** [comment]
Now it does :) you're a genius.

**Comment by inamiy** [comment]
Thanks. I appreciate you sending me many good issues!
