### ISSUE TITLE
UITabBar jumps into middle of the screen on orientation change

### ISSUE THREAD

**Issue by ghost** [inamiy/YIFullScreenScroll#8]
Here's a example project:

https://github.com/mylittlehero/FullScreenTabBarIssue.git

Start the app in landscape mode and touch a cell. The tabBar will jump in the middle of the screen.

**Comment by inamiy** [comment]
Thanks. Please try the one I just committed.

**Comment by ghost** [comment]
Great :). Now it works like a charm!
